"""
Shared utilities — no circular imports allowed here.
"""

import re

# All major NSE stocks — NIFTY50 + NEXT50 + MIDCAP150 + F&O + new-age
NSE_KNOWN_SYMBOLS = {
    # NIFTY 50
    "ADANIPORTS","ADANIENT","APOLLOHOSP","ASIANPAINT","AXISBANK","BAJAJ-AUTO",
    "BAJFINANCE","BAJAJFINSV","BPCL","BHARTIARTL","BRITANNIA","CIPLA","COALINDIA",
    "DIVISLAB","DRREDDY","EICHERMOT","GRASIM","HCLTECH","HDFCBANK","HDFCLIFE",
    "HEROMOTOCO","HINDALCO","HINDUNILVR","ICICIBANK","INDUSINDBK","INFY","ITC",
    "JSWSTEEL","KOTAKBANK","LT","LTIM","M&M","MARUTI","NESTLEIND","NTPC","ONGC",
    "POWERGRID","RELIANCE","SBILIFE","SBIN","SUNPHARMA","TATACONSUM","TATAMOTORS",
    "TATASTEEL","TCS","TECHM","TITAN","ULTRACEMCO","WIPRO","ICICIPRULI",
    # NIFTY NEXT 50
    "ABB","ADANIGREEN","ADANITRANS","AMBUJACEM","ATGL","BAJAJHLDNG","BANKBARODA",
    "BEL","BERGEPAINT","BOSCHLTD","CANBK","CHOLAFIN","COLPAL","CUMMINSIND",
    "DLF","GAIL","GODREJCP","GODREJPROP","HAVELLS","INDIGO","INDUSTOWER",
    "IRCTC","JINDALSTEL","JUBLFOOD","LICI","LODHA","LUPIN","MARICO","NAUKRI",
    "OFSS","PAGEIND","PERSISTENT","PIIND","PNB","POLYCAB","RECLTD","SHRIRAMFIN",
    "SIEMENS","SRF","TATAPOWER","TORNTPHARM","TRENT","UNIONBANK","UPL","VEDL",
    "ZYDUSLIFE","MCDOWELL-N","MUTHOOTFIN",
    # NIFTY MIDCAP 150
    "AUROPHARMA","BALKRISIND","BATAINDIA","BHEL","BIOCON","BLUEDART","CESC",
    "CROMPTON","DALBHARAT","DEEPAKNTR","DIXON","ESCORTS","EXIDEIND","FEDERALBNK",
    "GLENMARK","GMRINFRA","GNFC","GRANULES","GUJGASLTD","HFCL","IDFCFIRSTB",
    "IEX","IIFL","INDHOTEL","IOB","IPCALAB","JKCEMENT","JSWENERGY","KAJARIACER",
    "KANSAINER","KEI","KPITTECH","LAURUSLABS","LICHSGFIN","LTTS","MANAPPURAM",
    "MAXHEALTH","METROPOLIS","MGL","MOTHERSON","MPHASIS","MRPL","NATCOPHARM",
    "NBCC","NCC","NMDC","OBEROIRLTY","PETRONET","PFC","PHOENIXLTD","PIDILITIND",
    "PRESTIGE","RAMCOCEM","RBLBANK","SAIL","SJVN","SOLARINDS","SONACOMS",
    "SUNDRMFAST","SUPREMEIND","SYNGENE","TATACHEM","TATACOMM","TATAELXSI",
    "THERMAX","TIINDIA","TORNTPOWER","TRIDENT","TVSMOTORS","UBL","VOLTAS",
    "ZEEL","ZOMATO","NYKAA","DELHIVERY","POLICYBZR","PAYTM","SWIGGY",
    # PSU & Banks
    "IOC","HINDPETRO","NLCINDIA","RVNL","IRFC","HUDCO","IREDA",
    "CENTRALBANK","INDIANB","MAHABANK","UCOBANK","BANDHANBNK","AUBANK",
    "EQUITASBNK","UJJIVANSFB",
    # Popular F&O stocks
    "ADANIPOWER","APLAPOLLO","ASTRAL","CHAMBLFERT","COFORGE",
    "CONCOR","CYIENT","DATAPATTNS","FIVESTAR","GLAXO","GRINDWELL",
    "HAPPSTMNDS","HINDCOPPER","INOXWIND","IRCON","ISEC","JBCHEPHARM",
    "KFINTECH","KIMS","LALPATHLAB","LATENTVIEW","MAPMYINDIA","MEDANTA",
    "NUVAMA","OLECTRA","PGHH","PNBHOUSING","RADICO","RAINBOW","ROUTE",
    "SAPPHIRE","SCHAEFFLER","SENCO","SOBHA","SUNTV","TANLA",
    "TRITURBINE","UNOMINDA","UTIAMC","VAIBHAVGBL","VBL","WELSPUNLIV","ZENSARTECH",
    "AARTIIND",
    # Chemicals & FMCG
    "ATUL","BASF","BAYER","DEEPAKFERT","FINEORG","GALAXYSURF","NAVINFLUOR",
    "NOCIL","RALLIS","SUDARSCHEM","VINATIORG","DABUR","EMAMILTD","JYOTHYLAB",
    "VSTIND","TATACONSUM",
    # Insurance & AMC
    "ABSLAMC","ANGELONE","CAMS","HDFCAMC","ICICIGI","MFSL","NIACL","SBICARD",
    "STARHEALTH",
}


def extract_stock_mentions(text: str) -> list:
    """Extract NSE stock symbols mentioned in user message for live price lookup."""
    words = set(re.findall(r'\b[A-Z][A-Z0-9&\-]{1,14}\b', text.upper()))
    return list(words & NSE_KNOWN_SYMBOLS)
